/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cute_robot.glb --transform 
Files: cute_robot.glb [131.1KB] > F:\Porfolio\sandeep-portfolio\public\models\cute_robot-transformed.glb [21.87KB] (83%)
Author: victory_mirosya (https://sketchfab.com/victory_mirosya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-robot-6aadb75f596742ada2814ad4593f0032
Title: cute robot
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function CuteRobot(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/cute_robot-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0.005, 1.227, 0.854]} rotation={[Math.PI / 2, 0, 0]} scale={[0.153, 0.285, 0.153]} />
        <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial002} position={[0.005, 1.227, 0.854]} rotation={[Math.PI / 2, 0, 0]} scale={[0.153, 0.285, 0.153]} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial003} position={[0.005, 1.227, 0.854]} rotation={[Math.PI / 2, 0, 0]} scale={[0.153, 0.285, 0.153]} />
        <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.PaletteMaterial004} position={[0, 0, -0.279]} rotation={[0, 0.473, 0]} scale={[0.892, 0.611, 0.611]} />
        <mesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={materials.PaletteMaterial005} morphTargetDictionary={nodes.mesh_2.morphTargetDictionary} morphTargetInfluences={nodes.mesh_2.morphTargetInfluences} position={[0.473, 1.235, 0.136]} rotation={[0, 0, -Math.PI / 2]} scale={[0.168, 0.21, 0.09]} />
        <mesh name="mesh_3" geometry={nodes.mesh_3.geometry} material={materials.PaletteMaterial005} position={[0.473, 1.235, -0.138]} rotation={[0, 0, -Math.PI / 2]} scale={[0.168, 0.21, 0.09]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cute_robot-transformed.glb')
