/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 boysandeep.glb -T 
Files: boysandeep.glb [958.38KB] > F:\Porfolio\sandeep-portfolio\public\models\boysandeep-transformed.glb [437.62KB] (54%)
*/

import React, { useRef } from 'react'
import gsap from 'gsap'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useGSAP } from '@gsap/react'

export function Herosandeep(props) {
  const { scene } = useGLTF('/models/boysandeep-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  const group = useRef();
  const mouse = useRef({ x: 0, y: 0 });
  const introOffset = useRef({ y: 2 });
  const headTarget  = useRef({ x: 0, y: 0 });
  const spineTarget = useRef({ x: 0, y: 0 });
  const hipsTarget  = useRef({ x: 0, y: 0 });

  useGSAP(() => {
    gsap.to(introOffset.current, {
      y: 0.2,
      duration: 1.8,
      ease: 'power3.out',
    });

    const handleMouseMove = (event) => {
      mouse.current.x = (event.clientX / window.innerWidth) * 2 - 1;
      mouse.current.y = -(event.clientY / window.innerHeight) * 2 + 1;
    };

    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  }, []);

  useFrame((_, delta) => {
    if (!group.current) return;

    const headLerp  = 1 - Math.pow(0.05, delta);
    const spineLerp = 1 - Math.pow(0.02, delta);
    const hipsLerp  = 1 - Math.pow(0.06, delta);

    const targetX = mouse.current.x;
    const targetY = mouse.current.y;

    headTarget.current.x  += (targetX * 0.8  - headTarget.current.x)  * headLerp;
    headTarget.current.y  += (-targetY * 0.8  - headTarget.current.y)  * headLerp;

    spineTarget.current.x += (targetX * 0.3  - spineTarget.current.x) * spineLerp;
    spineTarget.current.y += (-targetY * 0.25 - spineTarget.current.y) * spineLerp;

    hipsTarget.current.x  += (targetX * 0.1  - hipsTarget.current.x)  * hipsLerp;
    hipsTarget.current.y  += (-targetY * 0.1  - hipsTarget.current.y)  * hipsLerp;

    const head   = group.current.getObjectByName('Head');
    const neck   = group.current.getObjectByName('Neck');
    const spine2 = group.current.getObjectByName('Spine2');
    const spine1 = group.current.getObjectByName('Spine1');
    const spine  = group.current.getObjectByName('Spine');
    const hips   = group.current.getObjectByName('Hips');

    const iY = introOffset.current.y;

    if (head) {
      head.rotation.y = headTarget.current.x;
      head.rotation.x = headTarget.current.y + iY;
    }
    if (neck) {
      neck.rotation.y = headTarget.current.x * 0.5;
      neck.rotation.x = (headTarget.current.y + iY) * 0.3;
    }
    if (spine2) {
      spine2.rotation.y = spineTarget.current.x * 0.6;
      spine2.rotation.x = spineTarget.current.y * 0.3;
    }
    if (spine1) {
      spine1.rotation.y = spineTarget.current.x * 0.3;
    }
    if (spine) {
      spine.rotation.y = hipsTarget.current.x * 0.5;
    }
    if (hips) {
      hips.rotation.y = hipsTarget.current.x * 0.3;
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Glasses.geometry} material={materials.Wolf3D_Glasses} skeleton={nodes.Wolf3D_Glasses.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
      <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
      <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('/models/boysandeep-transformed.glb')